version: '3'

#Use docker compose for easier control, and scaling of containers for additional services
services:
  database:
    build: .
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: dealership_db
